# Generated by Django 4.2 on 2023-04-06 09:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=400, verbose_name='URL')),
                ('description', models.CharField(max_length=440, verbose_name='Краткое описание страницы')),
                ('body', ckeditor.fields.RichTextField(max_length=1200, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страницу',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
